[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.30.0"
hooks = [
    { id = "gitleaks" },
]
[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "check-builtin-literals" },
    { id = "check-executables-have-shebangs" },
    { id = "check-merge-conflict"},
    { id = "check-toml" },
    { id = "requirements-txt-fixer" },
    { id = "trailing-whitespace" },
]
